title: Vibe-Coding 101 @ SRH
description: Workshop materials
theme: jekyll-theme-minimal
nav:
  - title: Start
    url: /
  - divider: true
  - title: Basics
    children:
      - title: Vibe-Coding Input
        url: /theorie
      - title: Setup macOS
        url: /setup/mac
      - title: Setup Windows
        url: /setup/windows
  - divider: true
  - title: Tutorials
    children:
      - title: GitHub Tutorial
        url: /tutorials/github
      - title: Zed Tutorial
        url: /tutorials/zed
      - title: Opencode Tutorial
        url: /tutorials/opencode
  - divider: true
  - title: Projects
    children:
      - title: My first project
        url: /mein-erstes-projekt
      - title: Project inspiration
        url: /freies-projekt-inspiration
  - divider: true
  - title: Glossary
    url: /glossar
